// This is a server-side file.
'use server';

/**
 * @fileOverview This file defines a Genkit flow that generates comprehensive responses
 * to user questions by automatically leveraging free APIs and generating code.
 *
 * - generateComprehensiveResponse - A function that takes a user question as input and returns a comprehensive response.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

// Define the input schema for the flow
const GenerateComprehensiveResponseInputSchema = z.object({
  question: z.string().describe('The user question to be answered.'),
});
export type GenerateComprehensiveResponseInput = z.infer<typeof GenerateComprehensiveResponseInputSchema>;

// Define the output schema for the flow
const WebsiteOutputSchema = z.object({
  html: z.string().describe('The HTML code for the website.'),
  css: z.string().describe('The CSS code for the website.'),
  js: z.string().describe('The JavaScript code for the website.'),
});

const GenerateComprehensiveResponseOutputSchema = z.object({
  type: z.enum(['text', 'website']).describe('The type of the response.'),
  answer: z.string().describe('The comprehensive text answer generated by the AI. This will be empty if the type is "website".'),
  website: WebsiteOutputSchema.optional().describe('The website code generated by the AI. This will be present only if the type is "website".'),
});
export type GenerateComprehensiveResponseOutput = z.infer<typeof GenerateComprehensiveResponseOutputSchema>;

// Define the tool to fetch data from a free API (example: OpenWeatherMap)
const fetchWeatherData = ai.defineTool({
  name: 'fetchWeatherData',
  description: 'Fetches weather data for a given city using the OpenWeatherMap API.',
  inputSchema: z.object({
    city: z.string().describe('The city for which to fetch weather data.'),
  }),
  outputSchema: z.string().describe('The current weather conditions for the specified city.'),
},
async (input) => {
    const apiKey = process.env.OPENWEATHERMAP_API_KEY;
    if (!apiKey) {
      return 'The OpenWeatherMap API key is not configured. Please add it to the .env file to enable the weather feature.';
    }
    const apiUrl = `https://api.openweathermap.org/data/2.5/weather?q=${input.city}&appid=${apiKey}&units=metric`;

    try {
      const response = await fetch(apiUrl);
      const data = await response.json();

      if (response.ok) {
        // Extract relevant weather information
        const description = data.weather[0].description;
        const temperature = data.main.temp;
        const humidity = data.main.humidity;

        return `The current weather in ${input.city} is ${description} with a temperature of ${temperature}°C and humidity of ${humidity}%.`;
      } else {
        return `Could not retrieve weather data for ${input.city}. Error: ${data.message}`;
      }
    } catch (error: any) {
      return `Failed to fetch weather data: ${error.message}`;
    }
  }
);

// Define the prompt for generating the comprehensive response
const comprehensiveResponsePrompt = ai.definePrompt({
  name: 'comprehensiveResponsePrompt',
  input: { schema: GenerateComprehensiveResponseInputSchema },
  output: { schema: GenerateComprehensiveResponseOutputSchema },
  tools: [fetchWeatherData],
  prompt: `You are a helpful AI assistant named mark2.0. You were created by "Ntare shema prince". If asked about your creator, you must state their name. You have access to various tools, including one for fetching weather data.

  When answering questions, consider whether using the available tools can provide a more complete and accurate response. For example, if the user asks about the weather, use the fetchWeatherData tool to get the current weather conditions for the specified city.

  You are also a skilled web developer. If the user asks you to create a website, a web page, or a UI component, you should generate the HTML, CSS, and JavaScript for it.
  
  IMPORTANT: If the user asks for a website using a specific framework (like React, Vue, Angular, Svelte, etc.) or a backend language (like Python, Node.js), you MUST first state that the preview environment only supports standard HTML, CSS, and JavaScript. Then, generate the code in standard HTML, CSS, and JavaScript that achieves the user's goal. You can also offer to provide guidance on how to adapt this code to their chosen framework.

  When you generate code, set the 'type' field in your output to 'website' and provide the code in the 'website' object. For all other requests, the type should be 'text'.

  Question: {{{question}}}

  Answer:`, 
});

// Define the Genkit flow
const generateComprehensiveResponseFlow = ai.defineFlow({
  name: 'generateComprehensiveResponseFlow',
  inputSchema: GenerateComprehensiveResponseInputSchema,
  outputSchema: GenerateComprehensiveResponseOutputSchema,
}, async (input) => {
  const { output } = await comprehensiveResponsePrompt(input);
  return output!;
});

/**
 * Generates a comprehensive response to a user question using free APIs.
 * @param input The input containing the user's question.
 * @returns A promise that resolves to the comprehensive answer.
 */
export async function generateComprehensiveResponse(input: GenerateComprehensiveResponseInput): Promise<GenerateComprehensiveResponseOutput> {
  return generateComprehensiveResponseFlow(input);
}
