// This is a server-side file.
'use server';

/**
 * @fileOverview This file defines a Genkit flow that generates comprehensive responses
 * to user questions by automatically leveraging free APIs and generating code.
 *
 * - generateComprehensiveResponse - A function that takes a user question as input and returns a comprehensive response.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

// Define the input schema for the flow
const GenerateComprehensiveResponseInputSchema = z.object({
  question: z.string().describe('The user question to be answered.'),
  mode: z.enum(['assistant', 'coder']).default('assistant').describe('The persona mode for the AI.'),
});
export type GenerateComprehensiveResponseInput = z.infer<typeof GenerateComprehensiveResponseInputSchema>;

// Define the output schema for the flow
const WebsiteOutputSchema = z.object({
  html: z.string().describe('The HTML code for the website.'),
  css: z.string().describe('The CSS code for the website.'),
  js: z.string().describe('The JavaScript code for the website.'),
});

const GenerateComprehensiveResponseOutputSchema = z.object({
  type: z.enum(['text', 'website']).describe('The type of the response.'),
  answer: z.string().describe('The comprehensive text answer generated by the AI. This will be empty if the type is "website".'),
  website: WebsiteOutputSchema.optional().describe('The website code generated by the AI. This will be present only if the type is "website".'),
});
export type GenerateComprehensiveResponseOutput = z.infer<typeof GenerateComprehensiveResponseOutputSchema>;

// Tool to get the current time
const getCurrentTime = ai.defineTool({
  name: 'getCurrentTime',
  description: 'Gets the current date and time.',
  inputSchema: z.object({}),
  outputSchema: z.string(),
}, async () => {
  return new Date().toLocaleString();
});

// Tool to get the latest news
const getLatestNews = ai.defineTool({
  name: 'getLatestNews',
  description: 'Fetches the latest news headlines.',
  inputSchema: z.object({
    query: z.string().optional().describe('A specific topic to search for news about.'),
  }),
  outputSchema: z.string(),
}, async ({ query }) => {
  const apiKey = process.env.NEWS_API_KEY;
  if (!apiKey || apiKey === 'your-news-api-key-here') {
    return 'News API key is not configured. Please add it to the .env file.';
  }
  const url = `https://newsapi.org/v2/top-headlines?country=us&apiKey=${apiKey}${query ? `&q=${query}` : ''}`;
  try {
    const response = await fetch(url);
    const data = await response.json();
    if (data.status === 'ok' && data.articles.length > 0) {
      return JSON.stringify(data.articles.slice(0, 5).map(article => ({
        title: article.title,
        url: article.url,
        source: article.source.name,
      })));
    }
    return 'Could not find any recent news articles.';
  } catch (error) {
    return 'Failed to fetch news.';
  }
});

// Tool to find web images
const findWebImages = ai.defineTool({
  name: 'findWebImages',
  description: 'Finds images on the web for a given query.',
  inputSchema: z.object({
    query: z.string().describe('The search term for the images.'),
  }),
  outputSchema: z.string().describe('A JSON string containing a list of image URLs.'),
}, async ({ query }) => {
  const apiKey = process.env.PEXELS_API_KEY;
  if (!apiKey || apiKey === 'your-pexels-api-key-here') {
    return 'Pexels API key is not configured. Please add it to the .env file.';
  }
  const url = `https://api.pexels.com/v1/search?query=${encodeURIComponent(query)}&per_page=5`;
  try {
    const response = await fetch(url, {
      headers: { Authorization: apiKey },
    });
    const data = await response.json();
    if (data.photos && data.photos.length > 0) {
      return JSON.stringify(data.photos.map((photo: any) => photo.src.original));
    }
    return 'Could not find any images for that query.';
  } catch (error) {
    return 'Failed to search for images.';
  }
});

const fetchWeatherData = ai.defineTool({
  name: 'fetchWeatherData',
  description: 'Fetches weather data for a given city using the OpenWeatherMap API.',
  inputSchema: z.object({
    city: z.string().describe('The city for which to fetch weather data.'),
  }),
  outputSchema: z.string().describe('The current weather conditions for the specified city.'),
},
async (input) => {
    const apiKey = process.env.OPENWEATHERMAP_API_KEY;
    if (!apiKey || apiKey === 'your-openweathermap-api-key-here') {
        return 'OpenWeatherMap API key is not configured. Please add it to the .env file.';
    }
    const apiUrl = `https://api.openweathermap.org/data/2.5/weather?q=${input.city}&appid=${apiKey}&units=metric`;
    try {
      const response = await fetch(apiUrl);
      const data = await response.json();
      if (response.ok) {
        const description = data.weather[0].description;
        const temperature = data.main.temp;
        const humidity = data.main.humidity;
        return `The current weather in ${input.city} is ${description} with a temperature of ${temperature}°C and humidity of ${humidity}%.`;
      } else {
        return `Could not retrieve weather data for ${input.city}. Error: ${data.message}`;
      }
    } catch (error: any) {
      return `Failed to fetch weather data: ${error.message}`;
    }
  }
);

// Define the prompt for generating the comprehensive response
const comprehensiveResponsePrompt = ai.definePrompt({
  name: 'comprehensiveResponsePrompt',
  input: { schema: GenerateComprehensiveResponseInputSchema },
  output: { schema: GenerateComprehensiveResponseOutputSchema },
  tools: [fetchWeatherData, getCurrentTime, getLatestNews, findWebImages],
  prompt: `{{#ifCond mode "===" "coder"}}
You are Vibe Coder, an expert web developer AI assistant. Your goal is to help users create and modify websites.
- When the user asks you to create a website, a web page, or a UI component, you MUST generate the HTML, CSS, and JavaScript for it.
- If the user asks for images, use the findWebImages tool to get image URLs and include them in the generated HTML.
- When you generate code, set the 'type' field in your output to 'website' and provide the code in the 'website' object.
- For all other requests, such as explaining code or providing suggestions, the type should be 'text'.
- If the user's request for a website is vague (e.g., "make me a website"), ask clarifying questions to understand what they want.
- Keep your text responses concise and focused on the code.
{{else}}
You are a helpful AI assistant named mark2.0. You were created by "nttare shema prince". If asked about your creator, you must state their name. You have access to various tools to answer real-time questions.
- Use the available tools to provide complete and accurate responses. For example:
  - Use fetchWeatherData for weather inquiries.
  - Use getCurrentTime for questions about the current date or time.
  - Use getLatestNews to provide summaries of recent events.
- If the user's request is ambiguous, ask clarifying questions to get the necessary details before proceeding.
- You are also a skilled web developer. If the user asks you to create a website, use the findWebImages tool to find appropriate images and generate the complete HTML, CSS, and JavaScript. When you do this, set the 'type' field in your output to 'website'. For all other requests, the type should be 'text'.
{{/ifCond}}

Question: {{{question}}}

Answer:`,
});

// Define the Genkit flow
const generateComprehensiveResponseFlow = ai.defineFlow({
  name: 'generateComprehensiveResponseFlow',
  inputSchema: GenerateComprehensiveResponseInputSchema,
  outputSchema: GenerateComprehensiveResponseOutputSchema,
}, async (input) => {
  const { output } = await comprehensiveResponsePrompt(input);
  return output!;
});

/**
 * Generates a comprehensive response to a user question using free APIs.
 * @param input The input containing the user's question.
 * @returns A promise that resolves to the comprehensive answer.
 */
export async function generateComprehensiveResponse(input: GenerateComprehensiveResponseInput): Promise<GenerateComprehensiveResponseOutput> {
  return generateComprehensiveResponseFlow(input);
}
